package com.obt.bcaaswallet.database;

import org.greenrobot.greendao.annotation.*;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "WALLET_INFO".
 */
@Entity
public class WalletInfo{

    @Id
    private Long id;
    private String bitcoinPublicKeyStr;
    private String bitcoinPrivateKeyWIFStr;
    private String bitcoinAddressStr;
    private String blockService;
    private String accessToken;
    private String password;

    @Generated(hash = 1144910350)
    public WalletInfo() {
    }

    public WalletInfo(Long id) {
        this.id = id;
    }

    @Generated(hash = 1830150709)
    public WalletInfo(Long id, String bitcoinPublicKeyStr, String bitcoinPrivateKeyWIFStr, String bitcoinAddressStr, String blockService, String accessToken, String password) {
        this.id = id;
        this.bitcoinPublicKeyStr = bitcoinPublicKeyStr;
        this.bitcoinPrivateKeyWIFStr = bitcoinPrivateKeyWIFStr;
        this.bitcoinAddressStr = bitcoinAddressStr;
        this.blockService = blockService;
        this.accessToken = accessToken;
        this.password = password;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBitcoinPublicKeyStr() {
        return bitcoinPublicKeyStr;
    }

    public void setBitcoinPublicKeyStr(String bitcoinPublicKeyStr) {
        this.bitcoinPublicKeyStr = bitcoinPublicKeyStr;
    }

    public String getBitcoinPrivateKeyWIFStr() {
        return bitcoinPrivateKeyWIFStr;
    }

    public void setBitcoinPrivateKeyWIFStr(String bitcoinPrivateKeyWIFStr) {
        this.bitcoinPrivateKeyWIFStr = bitcoinPrivateKeyWIFStr;
    }

    public String getBitcoinAddressStr() {
        return bitcoinAddressStr;
    }

    public void setBitcoinAddressStr(String bitcoinAddressStr) {
        this.bitcoinAddressStr = bitcoinAddressStr;
    }

    public String getBlockService() {
        return blockService;
    }

    public void setBlockService(String blockService) {
        this.blockService = blockService;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "WalletInfo{" +
                "id=" + id +
                ", bitcoinPublicKeyStr='" + bitcoinPublicKeyStr + '\'' +
                ", bitcoinPrivateKeyWIFStr='" + bitcoinPrivateKeyWIFStr + '\'' +
                ", bitcoinAddressStr='" + bitcoinAddressStr + '\'' +
                ", blockService='" + blockService + '\'' +
                ", accessToken='" + accessToken + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
